### ISSUE TITLE
Importing activeRequests throws error

### ISSUE THREAD

**Issue by Svetislavoid** [kjleitz/active-requests#8]
Hi @kjleitz!

I'm trying to implement active-requests into an existing React project (created with create-react-app). After installing it using npm, I imported `activeRequests` in `App.js` file but the app immediately throws an error, shown on an image below:

![npm-active-requests-issue](https://user-images.githubusercontent.com/16430252/121493601-47397980-c9d8-11eb-9ca4-62f1dfa583cd.png)

It looks like that everything is working as expected though, I can console log `activeRequests` and can see all the properties and methods it has. I just can't get rid of the error that pops up on the screen whenever a page is reloaded (except by clicking on the 'x' in the top right corner of the error, but that's not a solution).

I tried importing `activeRequests` in other files, tried also importing it in a new React project, but the error is always there.

I know that I can also import a CDN script (tried that and it works), but that isn't an option for me as my project does not allow external resources in production.

Am I doing something wrong here or is the issue in the package itself?

**Edit:** I noticed that when built with `output.globalObject` removed from `webpack.config.js`, the error is gone. Can you please check if that 'hack' you added can/should be removed?

Thanks!

**Comment by kjleitz** [comment]
Oh, interesting! Thanks for the report, @Svetislavoid. I'll check it out.

**Comment by kjleitz** [comment]
Sorry it took so long @Svetislavoid, I got a bit busy! This issue is now fixed in v1.1.0, and a new version has been released. Thanks again for reporting!
